-- (Safe to re-run: rows that already exist are skipped.)
-- Surokkha BD: seed data for quiz_questions (Phase 5)
-- Generated from the existing, already-authored myths/facts and "before" guidance
-- in src/content/hazards/*.json (see docs/rules.md: never invent safety facts).
-- MCQ distractors reuse real "before" advice from OTHER hazards, so every option
-- shown is real, sourced advice -- just not the right advice for this hazard.

insert into quiz_questions (hazard_slug, question_en, question_bn, options_en, options_bn, answer_index, explanation_en, explanation_bn)
select * from (values
  ('cold-wave-fog', 'True or false: "A coal or charcoal fire in a closed room is a good way to stay warm."', 'সত্য নাকি মিথ্যা: "বন্ধ ঘরে কয়লা বা কাঠের আগুন গরম থাকার ভালো উপায়।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Burning charcoal or wood indoors can release carbon monoxide, which can kill. Keep the room ventilated.', 'ঘরের ভেতরে কয়লা বা কাঠ পোড়ালে কার্বন মনোক্সাইড তৈরি হয়, যা প্রাণঘাতী। ঘরে বাতাস চলাচলের ব্যবস্থা রাখুন।'),
  ('cold-wave-fog', 'Which of these is good advice to prepare for a cold wave fog?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Get warm clothes and blankets ready before winter.', 'Watch for warnings about heavy rain in the upstream hills, including in India.', 'Store drinking water and use it carefully.', 'Do not cut hills or live at the foot or edge of a steep slope if you can avoid it.'], array['শীতের আগে গরম কাপড় ও কম্বল প্রস্তুত রাখুন।', 'উজানের পাহাড়ে, ভারতসহ, ভারী বৃষ্টির সতর্কবার্তার দিকে নজর রাখুন।', 'খাবার পানি মজুত রাখুন এবং হিসাব করে ব্যবহার করুন।', 'পাহাড় কাটবেন না এবং সম্ভব হলে খাড়া ঢালের পাদদেশে বা কিনারায় থাকবেন না।'], 0, 'Preparing for this hazard: Get warm clothes and blankets ready before winter.', 'এই দুর্যোগের প্রস্তুতি: শীতের আগে গরম কাপড় ও কম্বল প্রস্তুত রাখুন।'),
  ('cyclone', 'True or false: "I survived a storm before, so I can stay home this time."', 'সত্য নাকি মিথ্যা: "আগে ঝড় সামলেছি, তাই এবার বাড়িতেই থাকতে পারব।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Every storm is different, and a surge can be far more dangerous than the wind. Follow the signals.', 'প্রতিটি ঝড় আলাদা, আর জলোচ্ছ্বাস বাতাসের চেয়েও বিপজ্জনক হতে পারে। সংকেত মেনে চলুন।'),
  ('cyclone', 'Which of these is good advice to prepare for a cyclone?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Check the weather before going to fields or on the water.', 'Fix tall shelves and heavy furniture to the wall. Keep heavy items low.', 'Know your nearest cyclone shelter and the safest route to it.', 'Learn the signs of heat illness: heavy sweating, dizziness, headache, and nausea.'], array['মাঠে বা পানিতে যাওয়ার আগে আবহাওয়ার খবর দেখুন।', 'লম্বা তাক ও ভারী আসবাব দেয়ালের সাথে আটকে রাখুন। ভারী জিনিস নিচে রাখুন।', 'আপনার নিকটতম ঘূর্ণিঝড় আশ্রয়কেন্দ্র ও সেখানে যাওয়ার নিরাপদ পথ জেনে রাখুন।', 'গরমজনিত অসুস্থতার লক্ষণ জানুন: প্রচুর ঘাম, মাথা ঘোরা, মাথাব্যথা ও বমি বমি ভাব।'], 2, 'Preparing for this hazard: Know your nearest cyclone shelter and the safest route to it.', 'এই দুর্যোগের প্রস্তুতি: আপনার নিকটতম ঘূর্ণিঝড় আশ্রয়কেন্দ্র ও সেখানে যাওয়ার নিরাপদ পথ জেনে রাখুন।'),
  ('drought', 'True or false: "Drought only means there is no rain."', 'সত্য নাকি মিথ্যা: "খরা মানে শুধু বৃষ্টি না হওয়া।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Falling groundwater and repeated dry spells can cause shortages even when some rain falls.', 'কিছু বৃষ্টি হলেও ভূগর্ভস্থ পানির স্তর নামা ও বারবার শুষ্ক সময়ের কারণে সংকট হতে পারে।'),
  ('drought', 'Which of these is good advice to prepare for a drought?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Check forecasts and watch for dark, fast-moving clouds.', 'Watch for warnings about heavy rain in the upstream hills, including in India.', 'Store drinking water and use it carefully.', 'Do not cut hills or live at the foot or edge of a steep slope if you can avoid it.'], array['পূর্বাভাস দেখুন এবং কালো, দ্রুত সরে আসা মেঘের দিকে নজর রাখুন।', 'উজানের পাহাড়ে, ভারতসহ, ভারী বৃষ্টির সতর্কবার্তার দিকে নজর রাখুন।', 'খাবার পানি মজুত রাখুন এবং হিসাব করে ব্যবহার করুন।', 'পাহাড় কাটবেন না এবং সম্ভব হলে খাড়া ঢালের পাদদেশে বা কিনারায় থাকবেন না।'], 2, 'Preparing for this hazard: Store drinking water and use it carefully.', 'এই দুর্যোগের প্রস্তুতি: খাবার পানি মজুত রাখুন এবং হিসাব করে ব্যবহার করুন।'),
  ('earthquake', 'True or false: "Stand in a doorway during an earthquake."', 'সত্য নাকি মিথ্যা: "ভূমিকম্পের সময় দরজার চৌকাঠে দাঁড়ান।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Drop, cover, and hold on under a sturdy table instead. A doorway is not safer in most buildings.', 'বরং শক্ত টেবিলের নিচে বসে মাথা ঢেকে ধরে থাকুন। বেশিরভাগ ভবনে দরজার চৌকাঠ বেশি নিরাপদ নয়।'),
  ('earthquake', 'Which of these is good advice to prepare for a earthquake?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Learn the signs of heat illness: heavy sweating, dizziness, headache, and nausea.', 'Watch the bank for cracks, sinking ground, or leaning trees.', 'Check the weather before going to fields or on the water.', 'Fix tall shelves and heavy furniture to the wall. Keep heavy items low.'], array['গরমজনিত অসুস্থতার লক্ষণ জানুন: প্রচুর ঘাম, মাথা ঘোরা, মাথাব্যথা ও বমি বমি ভাব।', 'পাড়ে ফাটল, দেবে যাওয়া মাটি বা হেলে পড়া গাছ আছে কি না লক্ষ রাখুন।', 'মাঠে বা পানিতে যাওয়ার আগে আবহাওয়ার খবর দেখুন।', 'লম্বা তাক ও ভারী আসবাব দেয়ালের সাথে আটকে রাখুন। ভারী জিনিস নিচে রাখুন।'], 3, 'Preparing for this hazard: Fix tall shelves and heavy furniture to the wall. Keep heavy items low.', 'এই দুর্যোগের প্রস্তুতি: লম্বা তাক ও ভারী আসবাব দেয়ালের সাথে আটকে রাখুন। ভারী জিনিস নিচে রাখুন।'),
  ('flash-flood', 'True or false: "Flash floods only happen where it is raining nearby."', 'সত্য নাকি মিথ্যা: "আশপাশে বৃষ্টি হলেই কেবল আকস্মিক বন্যা হয়।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Rain far upstream can flood a haor within hours, even under clear skies.', 'অনেক উজানের বৃষ্টিতে আকাশ পরিষ্কার থাকলেও কয়েক ঘণ্টায় হাওর প্লাবিত হতে পারে।'),
  ('flash-flood', 'Which of these is good advice to prepare for a flash flood?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Watch for warnings about heavy rain in the upstream hills, including in India.', 'Follow flood forecasts and warnings from official sources.', 'Check forecasts and watch for dark, fast-moving clouds.', 'Do not cut hills or live at the foot or edge of a steep slope if you can avoid it.'], array['উজানের পাহাড়ে, ভারতসহ, ভারী বৃষ্টির সতর্কবার্তার দিকে নজর রাখুন।', 'সরকারি উৎস থেকে বন্যার পূর্বাভাস ও সতর্কবার্তা অনুসরণ করুন।', 'পূর্বাভাস দেখুন এবং কালো, দ্রুত সরে আসা মেঘের দিকে নজর রাখুন।', 'পাহাড় কাটবেন না এবং সম্ভব হলে খাড়া ঢালের পাদদেশে বা কিনারায় থাকবেন না।'], 0, 'Preparing for this hazard: Watch for warnings about heavy rain in the upstream hills, including in India.', 'এই দুর্যোগের প্রস্তুতি: উজানের পাহাড়ে, ভারতসহ, ভারী বৃষ্টির সতর্কবার্তার দিকে নজর রাখুন।'),
  ('heatwave', 'True or false: "I only need to drink when I feel thirsty."', 'সত্য নাকি মিথ্যা: "পিপাসা পেলেই শুধু পানি খেলে চলবে।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Thirst comes late. In the heat, drink water regularly through the day.', 'পিপাসা দেরিতে পায়। গরমে সারা দিন নিয়মিত পানি পান করুন।'),
  ('heatwave', 'Which of these is good advice to prepare for a heatwave?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Collect and store rainwater in clean, covered containers.', 'Check the weather before going to fields or on the water.', 'Learn the signs of heat illness: heavy sweating, dizziness, headache, and nausea.', 'Watch the bank for cracks, sinking ground, or leaning trees.'], array['বৃষ্টির পানি পরিষ্কার ঢাকনাযুক্ত পাত্রে সংগ্রহ ও সংরক্ষণ করুন।', 'মাঠে বা পানিতে যাওয়ার আগে আবহাওয়ার খবর দেখুন।', 'গরমজনিত অসুস্থতার লক্ষণ জানুন: প্রচুর ঘাম, মাথা ঘোরা, মাথাব্যথা ও বমি বমি ভাব।', 'পাড়ে ফাটল, দেবে যাওয়া মাটি বা হেলে পড়া গাছ আছে কি না লক্ষ রাখুন।'], 2, 'Preparing for this hazard: Learn the signs of heat illness: heavy sweating, dizziness, headache, and nausea.', 'এই দুর্যোগের প্রস্তুতি: গরমজনিত অসুস্থতার লক্ষণ জানুন: প্রচুর ঘাম, মাথা ঘোরা, মাথাব্যথা ও বমি বমি ভাব।'),
  ('landslide', 'True or false: "Landslides only happen while it is raining."', 'সত্য নাকি মিথ্যা: "ধস শুধু বৃষ্টির সময়ই হয়।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'They can also happen hours or days after heavy rain, when the soil is still soaked.', 'ভারী বৃষ্টির কয়েক ঘণ্টা বা দিন পরেও, মাটি ভেজা থাকলে ধস হতে পারে।'),
  ('landslide', 'Which of these is good advice to prepare for a landslide?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Follow flood forecasts and warnings from official sources.', 'Check forecasts and watch for dark, fast-moving clouds.', 'Know that a strong or long earthquake near the coast is a natural warning.', 'Do not cut hills or live at the foot or edge of a steep slope if you can avoid it.'], array['সরকারি উৎস থেকে বন্যার পূর্বাভাস ও সতর্কবার্তা অনুসরণ করুন।', 'পূর্বাভাস দেখুন এবং কালো, দ্রুত সরে আসা মেঘের দিকে নজর রাখুন।', 'জানুন, উপকূলের কাছে শক্তিশালী বা দীর্ঘ ভূমিকম্প একটি স্বাভাবিক সতর্কসংকেত।', 'পাহাড় কাটবেন না এবং সম্ভব হলে খাড়া ঢালের পাদদেশে বা কিনারায় থাকবেন না।'], 3, 'Preparing for this hazard: Do not cut hills or live at the foot or edge of a steep slope if you can avoid it.', 'এই দুর্যোগের প্রস্তুতি: পাহাড় কাটবেন না এবং সম্ভব হলে খাড়া ঢালের পাদদেশে বা কিনারায় থাকবেন না।'),
  ('lightning', 'True or false: "Standing under a tree keeps you safe from lightning."', 'সত্য নাকি মিথ্যা: "গাছের নিচে দাঁড়ালে বজ্রপাত থেকে নিরাপদ থাকা যায়।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Trees attract strikes and are one of the most dangerous places to stand. Go into a strong building.', 'গাছে বজ্রপাত বেশি পড়ে, তাই গাছের নিচে দাঁড়ানো সবচেয়ে বিপজ্জনক। পাকা ঘরে আশ্রয় নিন।'),
  ('lightning', 'Which of these is good advice to prepare for a lightning?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Watch the bank for cracks, sinking ground, or leaning trees.', 'Never throw plastic or waste into drains. It blocks the water.', 'Collect and store rainwater in clean, covered containers.', 'Check the weather before going to fields or on the water.'], array['পাড়ে ফাটল, দেবে যাওয়া মাটি বা হেলে পড়া গাছ আছে কি না লক্ষ রাখুন।', 'ড্রেনে প্লাস্টিক বা আবর্জনা ফেলবেন না। এতে পানি আটকে যায়।', 'বৃষ্টির পানি পরিষ্কার ঢাকনাযুক্ত পাত্রে সংগ্রহ ও সংরক্ষণ করুন।', 'মাঠে বা পানিতে যাওয়ার আগে আবহাওয়ার খবর দেখুন।'], 3, 'Preparing for this hazard: Check the weather before going to fields or on the water.', 'এই দুর্যোগের প্রস্তুতি: মাঠে বা পানিতে যাওয়ার আগে আবহাওয়ার খবর দেখুন।'),
  ('nor-wester', 'True or false: "A kalbaishakhi is just a normal storm, so there is no need to go inside."', 'সত্য নাকি মিথ্যা: "কালবৈশাখী সাধারণ ঝড়, তাই ঘরে যাওয়ার দরকার নেই।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'These storms can bring damaging wind, lightning, and hail within minutes. Take shelter early.', 'এই ঝড়ে কয়েক মিনিটেই ক্ষতিকর বাতাস, বজ্রপাত ও শিলাবৃষ্টি হতে পারে। আগেই আশ্রয় নিন।'),
  ('nor-wester', 'Which of these is good advice to prepare for a nor wester?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Get warm clothes and blankets ready before winter.', 'Know that a strong or long earthquake near the coast is a natural warning.', 'Check forecasts and watch for dark, fast-moving clouds.', 'Follow flood forecasts and warnings from official sources.'], array['শীতের আগে গরম কাপড় ও কম্বল প্রস্তুত রাখুন।', 'জানুন, উপকূলের কাছে শক্তিশালী বা দীর্ঘ ভূমিকম্প একটি স্বাভাবিক সতর্কসংকেত।', 'পূর্বাভাস দেখুন এবং কালো, দ্রুত সরে আসা মেঘের দিকে নজর রাখুন।', 'সরকারি উৎস থেকে বন্যার পূর্বাভাস ও সতর্কবার্তা অনুসরণ করুন।'], 2, 'Preparing for this hazard: Check forecasts and watch for dark, fast-moving clouds.', 'এই দুর্যোগের প্রস্তুতি: পূর্বাভাস দেখুন এবং কালো, দ্রুত সরে আসা মেঘের দিকে নজর রাখুন।'),
  ('riverbank-erosion', 'True or false: "Erosion is slow, so there is always time to react."', 'সত্য নাকি মিথ্যা: "ভাঙন ধীরে হয়, তাই সবসময় সময় থাকে।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'A bank can collapse in minutes once cracks appear. Move at the first signs.', 'ফাটল দেখা দিলে কয়েক মিনিটেই পাড় ভেঙে পড়তে পারে। প্রথম লক্ষণেই সরে যান।'),
  ('riverbank-erosion', 'Which of these is good advice to prepare for a riverbank erosion?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Collect and store rainwater in clean, covered containers.', 'Know your nearest cyclone shelter and the safest route to it.', 'Never throw plastic or waste into drains. It blocks the water.', 'Watch the bank for cracks, sinking ground, or leaning trees.'], array['বৃষ্টির পানি পরিষ্কার ঢাকনাযুক্ত পাত্রে সংগ্রহ ও সংরক্ষণ করুন।', 'আপনার নিকটতম ঘূর্ণিঝড় আশ্রয়কেন্দ্র ও সেখানে যাওয়ার নিরাপদ পথ জেনে রাখুন।', 'ড্রেনে প্লাস্টিক বা আবর্জনা ফেলবেন না। এতে পানি আটকে যায়।', 'পাড়ে ফাটল, দেবে যাওয়া মাটি বা হেলে পড়া গাছ আছে কি না লক্ষ রাখুন।'], 3, 'Preparing for this hazard: Watch the bank for cracks, sinking ground, or leaning trees.', 'এই দুর্যোগের প্রস্তুতি: পাড়ে ফাটল, দেবে যাওয়া মাটি বা হেলে পড়া গাছ আছে কি না লক্ষ রাখুন।'),
  ('riverine-flood', 'True or false: "Floodwater that looks calm is safe to wade through."', 'সত্য নাকি মিথ্যা: "শান্ত দেখালে বন্যার পানিতে হেঁটে যাওয়া নিরাপদ।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Currents can be strong, and water can hide holes and hazards or carry disease. Stay out.', 'স্রোত প্রবল হতে পারে, পানির নিচে গর্ত বা বিপদ লুকিয়ে থাকতে পারে এবং রোগজীবাণু থাকতে পারে। পানিতে নামবেন না।'),
  ('riverine-flood', 'Which of these is good advice to prepare for a riverine flood?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Know that a strong or long earthquake near the coast is a natural warning.', 'Store drinking water and use it carefully.', 'Get warm clothes and blankets ready before winter.', 'Follow flood forecasts and warnings from official sources.'], array['জানুন, উপকূলের কাছে শক্তিশালী বা দীর্ঘ ভূমিকম্প একটি স্বাভাবিক সতর্কসংকেত।', 'খাবার পানি মজুত রাখুন এবং হিসাব করে ব্যবহার করুন।', 'শীতের আগে গরম কাপড় ও কম্বল প্রস্তুত রাখুন।', 'সরকারি উৎস থেকে বন্যার পূর্বাভাস ও সতর্কবার্তা অনুসরণ করুন।'], 3, 'Preparing for this hazard: Follow flood forecasts and warnings from official sources.', 'এই দুর্যোগের প্রস্তুতি: সরকারি উৎস থেকে বন্যার পূর্বাভাস ও সতর্কবার্তা অনুসরণ করুন।'),
  ('salinity', 'True or false: "Boiling salty water makes it safe to drink."', 'সত্য নাকি মিথ্যা: "লোনা পানি ফুটালে খাওয়ার উপযোগী হয়।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Boiling does not remove salt. Use stored rainwater or a low-salt source instead.', 'ফুটালে লবণ যায় না। বরং জমানো বৃষ্টির পানি বা কম লবণাক্ত উৎস ব্যবহার করুন।'),
  ('salinity', 'Which of these is good advice to prepare for a salinity?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Know your nearest cyclone shelter and the safest route to it.', 'Fix tall shelves and heavy furniture to the wall. Keep heavy items low.', 'Never throw plastic or waste into drains. It blocks the water.', 'Collect and store rainwater in clean, covered containers.'], array['আপনার নিকটতম ঘূর্ণিঝড় আশ্রয়কেন্দ্র ও সেখানে যাওয়ার নিরাপদ পথ জেনে রাখুন।', 'লম্বা তাক ও ভারী আসবাব দেয়ালের সাথে আটকে রাখুন। ভারী জিনিস নিচে রাখুন।', 'ড্রেনে প্লাস্টিক বা আবর্জনা ফেলবেন না। এতে পানি আটকে যায়।', 'বৃষ্টির পানি পরিষ্কার ঢাকনাযুক্ত পাত্রে সংগ্রহ ও সংরক্ষণ করুন।'], 3, 'Preparing for this hazard: Collect and store rainwater in clean, covered containers.', 'এই দুর্যোগের প্রস্তুতি: বৃষ্টির পানি পরিষ্কার ঢাকনাযুক্ত পাত্রে সংগ্রহ ও সংরক্ষণ করুন।'),
  ('tsunami', 'True or false: "A tsunami is one giant wave, so I can go back after the first one."', 'সত্য নাকি মিথ্যা: "সুনামি একটাই বিশাল ঢেউ, তাই প্রথমটির পর ফিরে যেতে পারি।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'Tsunamis come as a series of waves that can last for hours. Stay away until officials say it is safe.', 'সুনামি একের পর এক ঢেউ হয়ে আসে, যা কয়েক ঘণ্টা চলতে পারে। কর্তৃপক্ষ নিরাপদ না বলা পর্যন্ত দূরে থাকুন।'),
  ('tsunami', 'Which of these is good advice to prepare for a tsunami?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Get warm clothes and blankets ready before winter.', 'Store drinking water and use it carefully.', 'Know that a strong or long earthquake near the coast is a natural warning.', 'Watch for warnings about heavy rain in the upstream hills, including in India.'], array['শীতের আগে গরম কাপড় ও কম্বল প্রস্তুত রাখুন।', 'খাবার পানি মজুত রাখুন এবং হিসাব করে ব্যবহার করুন।', 'জানুন, উপকূলের কাছে শক্তিশালী বা দীর্ঘ ভূমিকম্প একটি স্বাভাবিক সতর্কসংকেত।', 'উজানের পাহাড়ে, ভারতসহ, ভারী বৃষ্টির সতর্কবার্তার দিকে নজর রাখুন।'], 2, 'Preparing for this hazard: Know that a strong or long earthquake near the coast is a natural warning.', 'এই দুর্যোগের প্রস্তুতি: জানুন, উপকূলের কাছে শক্তিশালী বা দীর্ঘ ভূমিকম্প একটি স্বাভাবিক সতর্কসংকেত।'),
  ('urban-waterlogging', 'True or false: "Standing water is only a nuisance."', 'সত্য নাকি মিথ্যা: "জমা পানি শুধু বিরক্তিকর।"', array['True', 'False'], array['সত্য', 'মিথ্যা'], 1, 'It can hide open manholes, carry disease, and pass electricity from damaged lines.', 'এতে খোলা ম্যানহোল লুকিয়ে থাকতে পারে, রোগজীবাণু থাকতে পারে এবং ক্ষতিগ্রস্ত তার থেকে বিদ্যুৎ ছড়াতে পারে।'),
  ('urban-waterlogging', 'Which of these is good advice to prepare for a urban waterlogging?', 'এই ধরনের দুর্যোগের জন্য প্রস্তুতি হিসেবে কোনটি সঠিক পরামর্শ?', array['Learn the signs of heat illness: heavy sweating, dizziness, headache, and nausea.', 'Never throw plastic or waste into drains. It blocks the water.', 'Know your nearest cyclone shelter and the safest route to it.', 'Fix tall shelves and heavy furniture to the wall. Keep heavy items low.'], array['গরমজনিত অসুস্থতার লক্ষণ জানুন: প্রচুর ঘাম, মাথা ঘোরা, মাথাব্যথা ও বমি বমি ভাব।', 'ড্রেনে প্লাস্টিক বা আবর্জনা ফেলবেন না। এতে পানি আটকে যায়।', 'আপনার নিকটতম ঘূর্ণিঝড় আশ্রয়কেন্দ্র ও সেখানে যাওয়ার নিরাপদ পথ জেনে রাখুন।', 'লম্বা তাক ও ভারী আসবাব দেয়ালের সাথে আটকে রাখুন। ভারী জিনিস নিচে রাখুন।'], 1, 'Preparing for this hazard: Never throw plastic or waste into drains. It blocks the water.', 'এই দুর্যোগের প্রস্তুতি: ড্রেনে প্লাস্টিক বা আবর্জনা ফেলবেন না। এতে পানি আটকে যায়।')
) as v(hazard_slug, question_en, question_bn, options_en, options_bn, answer_index, explanation_en, explanation_bn)
where not exists (select 1 from quiz_questions t where t.hazard_slug = v.hazard_slug and t.question_en = v.question_en);
